version: "3.9"
 
services: 
  webapi: 
    build: ./WebApi
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      DatabaseSettings__ConnectionString: "mongodb://aajnur:myPW@mongodb:27017"
 
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: aajnur
      MONGO_INITDB_ROOT_PASSWORD: myPW
    volumes:
      - mongovolume:/data/db
 
volumes:
  mongovolume: